name: CI – Karate Pix

on:
  push:
    branches: [ main, feat/** ]
  pull_request:
  workflow_dispatch:
    inputs:
      tags:
        description: "Tags do Karate (ex: @pix ou ~@wip)"
        required: false
        default: ""

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 11 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "11"
          cache: maven

      - name: Build & Test (Maven + Karate)
        shell: bash
        env:
          KARATE_TAGS: ${{ github.event.inputs.tags }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          # Auth A (client_credentials)
          AUTH_TOKEN_URL: ${{ secrets.AUTH_TOKEN_URL }}
          AUTH_CLIENT_ID: ${{ secrets.AUTH_CLIENT_ID }}
          AUTH_CLIENT_SECRET: ${{ secrets.AUTH_CLIENT_SECRET }}
          # Auth B (proxy GET)
          PIX_SECURITY_BASE_URL: ${{ secrets.PIX_SECURITY_BASE_URL }}
          PIX_SECURITY_TOKEN_PATH: ${{ secrets.PIX_SECURITY_TOKEN_PATH }}
          PIX_SECURITY_COMPANY_ID: ${{ secrets.PIX_SECURITY_COMPANY_ID }}
        run: |
          MVN="mvn -B -ntp test -Dtest=PixRunnerTest \
            -DSLACK_WEBHOOK_URL=\"$SLACK_WEBHOOK_URL\" \
            -DAUTH_TOKEN_URL=\"$AUTH_TOKEN_URL\" \
            -DAUTH_CLIENT_ID=\"$AUTH_CLIENT_ID\" \
            -DAUTH_CLIENT_SECRET=\"$AUTH_CLIENT_SECRET\" \
            -DPIX_SECURITY_BASE_URL=\"$PIX_SECURITY_BASE_URL\" \
            -DPIX_SECURITY_TOKEN_PATH=\"$PIX_SECURITY_TOKEN_PATH\" \
            -DPIX_SECURITY_COMPANY_ID=\"$PIX_SECURITY_COMPANY_ID\""

          if [ -n "$KARATE_TAGS" ]; then
            echo ">> Running with tags: $KARATE_TAGS"
            eval "$MVN -DTAGS=\"$KARATE_TAGS\""
          else
            eval "$MVN"
          fi


      - name: Upload reports (Karate/Surefire)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: karate-reports
          path: |
            target/karate-reports/**
            target/surefire-reports/**
            target/failsafe-reports/**
          if-no-files-found: warn

      - name: Publicar resumo no Job Summary
        if: always()
        shell: bash
        run: |
          echo "## Resultados do Karate" >> $GITHUB_STEP_SUMMARY
          echo "- Execução: \`${{ github.workflow }}\` (#${{ github.run_number }})" >> $GITHUB_STEP_SUMMARY
          echo "- Branch: \`${{ github.ref_name }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- Commit: \`${{ github.sha }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- Disparado por: \`${{ github.actor }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- Tags usadas: \`${{ github.event.inputs.tags || '—' }}\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Artefatos" >> $GITHUB_STEP_SUMMARY
          echo "- Baixe os relatórios: **karate-reports** (aba Artifacts desta execução)" >> $GITHUB_STEP_SUMMARY
